[project]
name = "proyecto-data-cleansing"
version = "0.1.0"
description = "Proyecto de ETL con extraccion de PDFs mediante OCR con visualizacion en Streamlit"
authors = [
    {name = "JoseDarioHernandez2",email = "josedariohernandez2@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas (<3.0.0)",
    "pytesseract (>=0.3.13,<0.4.0)",
    "pdfplumber (>=0.11.9,<0.12.0)",
    "streamlit (>=1.54.0,<2.0.0)",
    "pillow (>=12.1.1,<13.0.0)",
    "opencv-python (>=4.13.0.92,<5.0.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
    "faker (>=40.8.0,<41.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "plotly (>=6.6.0,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^26.1.0"
flake8 = "^7.3.0"

